apiVersion: v1
kind: Service
metadata:
  name: rds-proxy
spec:
  selector:
    app: rds-proxy
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: rds-proxy
    protocol: TCP
    port: 5432
    targetPort: 5432